### ISSUE TITLE
Resolve 404 link issues

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/sac-microsite#22]
These pages contain links to pages which 404

https://sac.jncc.gov.uk/site/england	https://sac.jncc.gov.uk/england
https://sac.jncc.gov.uk/site/scotland	https://sac.jncc.gov.uk/scotland
https://sac.jncc.gov.uk/site/northern-ireland	https://sac.jncc.gov.uk/northern-ireland
https://sac.jncc.gov.uk/site/wales	https://sac.jncc.gov.uk/wales
https://sac.jncc.gov.uk/site/offshore	https://sac.jncc.gov.uk/offshore

Could you resolve

Also please find attached a full list of all 404s now that we have a paid licence to screaming frog

[https://app.zenhub.com/files/138031480/5c0d3490-e3c2-4ee4-a8fc-0c9e240844b1/download](https://app.zenhub.com/files/138031480/5c0d3490-e3c2-4ee4-a8fc-0c9e240844b1/download)

also attached is a list of 301 redirects in place and i am not sure why

[https://app.zenhub.com/files/138031480/4b59189f-2622-443c-8f88-85f683783b82/download](https://app.zenhub.com/files/138031480/4b59189f-2622-443c-8f88-85f683783b82/download)

and also find attached a list of pdf files which dont resolve - and hoping they will do in future

[https://app.zenhub.com/files/138031480/ea160e29-1431-4168-be35-444478e581a4/download](https://app.zenhub.com/files/138031480/ea160e29-1431-4168-be35-444478e581a4/download)

**Comment by mattdebont** [comment]
Think all of these are now resolved apart from the links to other sites (none of them actually work so need to go back to the relevant team to either update them in the raw data or remove them)

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
the list of 404 in the attached spreadsheet are still present in the site
looks like its caused by this problem in the code
<P>The <A href=&quot;http://europa.eu.int/comm/environment/nature/hab-en.htm&quot;><I>Interpretation manual of European habitats</I>
could you review the list in the download and resolve please

**Comment by mattdebont** [comment]
Issues are resolved, but the links still 404 as they don't actually go anywhere this would need to be corrected at source in the database
